version: '3.9'
services:
  web:
    container_name: stable-diffusion-webui
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #   MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   TZ: Asia/Shanghai
    volumes:
      - ./webui:/usr/src
    restart: unless-stopped
